version: "2"

services:
  gem: &default
    build: .
    volumes:
      - .:/usr/src/app
      # for purposes of release
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - $HOME/.gem/credentials:/root/.gem/credentials
